### ISSUE TITLE
Make rules more DRY

### ISSUE THREAD

**Issue by huerlisi** [koffeinfrei/technologist#4]
Maybe we could also have a simpler implementation in the yaml file, something like using placeholders and an alias yml key:

~~~yaml
gem_rule: &gem_rule
  rules:
    - Gemfile: ^gem '%{name}'$
Rails:
  <<: *gem_rule
~~~

Initially I wanted to have classes instead of a yaml file, so that we could have general rule classes (e.g. GemRule) and inherit from them (e.g. RailsRule < GemRule). This would reduce duplication. Currently the yml is not dry at all, which makes me a bit unhappy.

**Comment by koffeinfrei** [comment]
I'm not very happy with the yml alias solution in PR #12. It's not very flexible.
Thinking about further rules as e.g.

* a rule that checks for the presence of a file
* a rule that checks for the presence of a directory

I think that going with a class-based solution makes more sense. In ruby yaml we can use serialized ruby objects which allows us to have rule defitions as the following:

```yml
Dashing:
  rules:
    - !ruby/object: FileContentRule
      file_name: README
      file_content: hello world
    - !ruby/object: GemRule # uses the downcased framework name
    - !ruby/object: GemRule # uses the explicit gem name
      gem_name: rails
    - !ruby/object: DirectoryPresenceRule
      directory_name: .meteor
    - !ruby/object: FilePresenceRule
      file_name: .meteor/packages
```

The `FileContentRule` rule would correspond to a class like so:

```ruby
class FileContentRule < Rule
  attr_accessor :file_name, file_content
end
```

This way we can also delegate the rule logic into the `Rule` classes instead of having every case piled up in the `FrameworkDetector` class.

**Comment by koffeinfrei** [comment]
Alternatively we could just eval the rules, which sounds a bit dangerous though. It would allow for simpler and shorter yml rule defintions:

```yml
Dashing:
  rules:
    - FileContentRule.new('README', 'hello world')
    - GemRule.new # uses the downcased framework name
    - GemRule.new('rails') # uses the explicit gem name
    - DirectoryPresenceRule.new('.meteor')
    - FilePresenceRule.new('.meteor/packages')
```

**Comment by koffeinfrei** [comment]
Regarding syntax there's also the following, which makes it shorter by using curly braces.

```yaml
Dashing:
  rules:
    - !ruby/object:GemRule { gem_name: 'dashing' }
```
